# Generated by Django 5.2.6 on 2025-09-16 13:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('product_views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.IntegerField()),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
