# Generated by Django 5.2.5 on 2025-09-15 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
